const cards = [
{
  name: "3rdRaikage",
  grade: "Argent",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/7c3pgw.jpg",
  Price: "800K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "A",
  grade: "Argent",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/amfh8w.jpg",
  Price: "600K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Ace",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/5vqryh.jpg",
  Price: "400K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Acnologia",
  grade: "Or",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/dy20sv.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Aiolia",
  grade: "Or",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/2mbwpb.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Akainu",
  grade: "Argent",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/qgrflk.jpg",
  Price: "800K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Akaza",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/o8waf7.jpg",
  Price: "450K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Aldebaran",
  grade: "Or",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/nvdw2s.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "AllForOne",
  grade: "Or",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/u18ovi.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "AllMight",
  grade: "Or",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/3x7bn9.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
}, 
{
  name: "Android16",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/tt79m2.jpg",
  Price: "100nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Android17(Dbz)",
  grade: "Argent",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/hohfci.jpg",
  Price: "200nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Android17(Dbs)",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/4bl67g.jpg",
  Price: "420nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Android18",
  grade: "Argent",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/b7neim.jpg",
  Price: "190nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Android19",
  grade: "Bronze",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/1lao5m.jpg",
  Price: "90nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Aoi",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/0rocs7.jpg",
  Price: "350k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Aokiji",
  grade: "Argent",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/dhy54u.jpg",
  Price: "800k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Aphrodite",
  grade: "Or",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/fairbf.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Asta",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/tjsj81.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Asta(Arc2)",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/2cd5ht.jpg",
  Price: "450k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Asuma",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/e9h4s7.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "AtomicSamurai",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/ihy73q.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Avdol",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/wgv1t5.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "BabyVegeta",
  grade: "Or",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/ahxz48.jpg",
  Price: "310nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Bakugo",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/gz77gh.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Bardock",
  grade: "Bronze",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/pidi5o.jpg",
  Price: "110nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Bang",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/yis1od.jpg",
  Price: "450k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Beerus",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/y9cgpo.jpg",
  Price: "530nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Bigmom",
  grade: "Argent",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/8qo8yi.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "BlackGoku",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/un7c3l.jpg",
  Price: "460nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Blizzard",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/q3qznx.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Bojack",
  grade: "Argent",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/ck3vpk.jpg",
  Price: "120nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Boro",
  grade: "Argent",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/bokgxn.jpg",
  Price: "700k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Boros",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/ofoqc5.jpg",
  Price: "2M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Borushiki",
  grade: "Argent",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/ayb8n5.jpg",
  Price: "800k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Boruto",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/8qzmzr.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Broly",
  grade: "Argent",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/au0pd6.jpg",
  Price: "300nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Broly(Dbs)",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/2qvkfx.jpg",
  Price: "480nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Brooks",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/kf359g.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Buhan",
  grade: "Or",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/2tbn9y.jpg",
  Price: "340nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Burter",
  grade: "Bronze",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/jkx88l.jpg",
  Price: "90nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Buu(super)",
  grade: "Or",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/5lfqpz.jpg",
  Price: "310nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Buu(Fat)",
  grade: "Or",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/xnl4el.jpg",
  Price: "300nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Buu(Kid)",
  grade: "Or",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/bb2e50.jpg",
  Price: "360nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Buutenks",
  grade: "Or",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/1gcugi.jpg",
  Price: "320nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
}, 
  
