const cards = [
{
  name: "3rdRaikage",
  grade: "Argent",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/7c3pgw.jpg",
  Price: "800K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "A",
  grade: "Argent",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/amfh8w.jpg",
  Price: "600K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Ace",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/5vqryh.jpg",
  Price: "400K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Acnologia",
  grade: "Or",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/dy20sv.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Aiolia",
  grade: "Or",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/2mbwpb.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Akainu",
  grade: "Argent",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/qgrflk.jpg",
  Price: "800K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Akaza",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/o8waf7.jpg",
  Price: "450K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Aldebaran",
  grade: "Or",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/nvdw2s.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "AllForOne",
  grade: "Or",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/u18ovi.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "AllMight",
  grade: "Or",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/3x7bn9.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
}, 
{
  name: "Android16",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/tt79m2.jpg",
  Price: "100nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Android17(Dbz)",
  grade: "Argent",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/hohfci.jpg",
  Price: "200nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Android17(Dbs)",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/4bl67g.jpg",
  Price: "420nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Android18",
  grade: "Argent",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/b7neim.jpg",
  Price: "190nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Android19",
  grade: "Bronze",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/1lao5m.jpg",
  Price: "90nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Aoi",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/0rocs7.jpg",
  Price: "350k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Aokiji",
  grade: "Argent",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/dhy54u.jpg",
  Price: "800k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Aphrodite",
  grade: "Or",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/fairbf.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Asta",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/tjsj81.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Asta(Arc2)",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/2cd5ht.jpg",
  Price: "450k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Asuma",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/e9h4s7.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "AtomicSamurai",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/ihy73q.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Avdol",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/wgv1t5.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "BabyVegeta",
  grade: "Or",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/ahxz48.jpg",
  Price: "310nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Bakugo",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/gz77gh.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Bardock",
  grade: "Bronze",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/pidi5o.jpg",
  Price: "110nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Bang",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/yis1od.jpg",
  Price: "450k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Beerus",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/y9cgpo.jpg",
  Price: "530nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Bigmom",
  grade: "Argent",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/8qo8yi.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "BlackGoku",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/un7c3l.jpg",
  Price: "460nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Blizzard",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/q3qznx.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Bojack",
  grade: "Argent",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/ck3vpk.jpg",
  Price: "120nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Boro",
  grade: "Argent",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/bokgxn.jpg",
  Price: "700k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Boros",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/ofoqc5.jpg",
  Price: "2M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Borushiki",
  grade: "Argent",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/ayb8n5.jpg",
  Price: "800k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Boruto",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/8qzmzr.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Broly",
  grade: "Argent",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/au0pd6.jpg",
  Price: "300nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Broly(Dbs)",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/2qvkfx.jpg",
  Price: "480nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Brooks",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/kf359g.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Buhan",
  grade: "Or",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/2tbn9y.jpg",
  Price: "340nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Burter",
  grade: "Bronze",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/jkx88l.jpg",
  Price: "90nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Buu(super)",
  grade: "Or",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/5lfqpz.jpg",
  Price: "310nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Buu(Fat)",
  grade: "Or",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/xnl4el.jpg",
  Price: "300nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Buu(Kid)",
  grade: "Or",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/bb2e50.jpg",
  Price: "360nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Buutenks",
  grade: "Or",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/1gcugi.jpg",
  Price: "320nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
}, 
  {
  name: "Cabba",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/rkdbjj.jpg",
  Price: "130nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Caufila",
  grade: "Argent",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/36yixr.jpg",
  Price: "200nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Cell(perfect)",
  grade: "Argent",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/3vv40w.jpg",
  Price: "280nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Cell(super)",
  grade: "Argent",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/6mi2yw.jpg",
  Price: "210nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Cell(base)",
  grade: "Bronze",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/xsh1ot.jpg",
  Price: "100nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Chiyo",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/5m69a3.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Choji",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/caghzt.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Choso",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/ww982g.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Chrollo",
  grade: "Argent",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/jpuv9q.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Code",
  grade: "Argent",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/bhq7oh.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Code(TBV)",
  grade: "Or",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/3vhh0l.jpg",
  Price: "1m200k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Crocodile",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/s8yttz.jpg",
  Price: "400k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Dabi",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/mjb4lj.jpg",
  Price: "400k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Dabura",
  grade: "Argent",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/edan2e.jpg",
  Price: "250nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Daemon",
  grade: "Or",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/s0sucf.jpg",
  Price: "1m800k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Dagon",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/cp5op5.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Daki",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/14j5af.jpg",
  Price: "150k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Dante",
  grade: "Or",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/n4dlb1.jpg",
  Price: "1m",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Danzo",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/jve2vt.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Darui",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/zs80ob.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Deathmask",
  grade: "Or",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/m6zwzi.jpg",
  Price: "1m500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "DeepSeaKing",
  grade: "Argent",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/yqiviz.jpg",
  Price: "700k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Deepa",
  grade: "Argent",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/epjakr.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Deidara",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/m0wm1s.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "DekuRogueHero",
  grade: "Argent",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/z5hzqb.jpg",
  Price: "700k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Deku",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/oh99hl.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Delta",
  grade: "Argent",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/h68hzb.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Denki",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/xerqh0.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Diavolo",
  grade: "Argent",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/yw5xb8.jpg",
  Price: "900k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Dio",
  grade: "Argent",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/32pw7w.jpg",
  Price: "900k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Doflamingo",
  grade: "Argent",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/v126vu.jpg",
  Price: "550k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Doma",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/4xdikn.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Dr.Gero",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/glg41l.jpg",
  Price: "600k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Dyspo",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/tr27u0.jpg",
  Price: "400nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Edward",
  grade: "Argent",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/q5bapo.jpg",
  Price: "1m200k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Eida",
  grade: "Or",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/5tx64p.jpg",
  Price: "1m800k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Eijiro",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/ljz7bk.jpg.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Endeavor",
  grade: "Argent",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/qcunun.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Enmu",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/x4hsa6.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Erza",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/otsr2e.jpg",
  Price: "450k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
}, 
{
  name: "FlashyFlash",
  grade: "Argent",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/git5xh.jpg",
  Price: "700k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Franky",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/t46wfj.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Frieza(super)",
  grade: "Argent",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/l97ml8.jpg",
  Price: "160nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Frieza(Base)",
  grade: "Bronze",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/i84paz.jpg",
  Price: "150nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Frieza(Golden)",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/dptorv.jpg",
  Price: "420nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Fuegoleon",
  grade: "Argent",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/2ocv94.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Fujitora",
  grade: "Argent",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/fslosy.jpg",
  Price: "700k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Fumikage",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/mucucs.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gaara(4GG)",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/v3nvkj.jpg",
  Price: "400k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gaara",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/cto2vg.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gajeel",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/8j1xus.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Garou",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/hbdp8l.jpg",
  Price: "450k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "GarouMonster",
  grade: "Argent",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/joebj6.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Garou(cosmic)",
  grade: "Or",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/6qyvrq.jpg",
  Price: "200nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Garp",
  grade: "Argent",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/20h2tl.jpg",
  Price: "800k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gauche",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/7gv4r9.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gengetsu",
  grade: "Argent",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/77h87l.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Genos(forme 2)",
  grade: "Argent",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/0p7zf7.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Genos",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/yvk9j3.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Geto",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/ytx8vy.jpg",
  Price: "400k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Geto(student)",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/0o4is7.jpg",
  Price: "350k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gildarts",
  grade: "Argent",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/41g7x4.jpg",
  Price: "900k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Ginyu",
  grade: "Bronze",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/1nhx0y.jpg",
  Price: "100nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Giorno",
  grade: "Or",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/5wvjc1.jpg",
  Price: "1m200k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Giyu",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/7ehtyz.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gogeta(Dbz)",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/ddf764.jpg",
  Price: "450nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gogeta(Dbs)",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/ru0r9d.jpg",
  Price: "550nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gogeta(SSJ4)",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/agk0gp.jpg",
  Price: "460nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gohan(Beast)",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/aj97ba.jpg",
  Price: "550nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gohan(Futur)",
  grade: "Argent",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/ghl7so.jpg",
  Price: "190nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gohan(SSj2)",
  grade: "Argent",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/ym9696.jpg",
  Price: "290nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gohan(SSJ)",
  grade: "Argent",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/d39zp8.jpg",
  Price: "150nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gohan(Buu arc)",
  grade: "Argent",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/r3za80.jpg",
  Price: "260nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gohan(Kid)",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/3b7ypn.jpg",
  Price: "90nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gohan(ultime)",
  grade: "Or",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/arcs79.jpg",
  Price: "350nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gohan(Dbs)",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/gfnu6y.jpg",
  Price: "430nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gojo",
  grade: "Argent",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/3hmg8k.jpg",
  Price: "800k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gojo(shinjuku)",
  grade: "Argent",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/jg1bvq.jpg",
  Price: "100nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gojo(Student)",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/qnha9o.jpg",
  Price: "50nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Goku(SSJnamek)",
  grade: "Argent",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/l4lt5w.jpg",
  Price: "180nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Goku(androids)",
  grade: "Argent",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/fpkm2x.jpg",
  Price: "270nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Goku(SSJ2)",
  grade: "Argent",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/0ib3ua.jpg",
  Price: "290nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Goku(name)",
  grade: "Bronze",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/vp7t7k.jpg",
  Price: "150nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Goku(debut)",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/bxvdah.jpg",
  Price: "100nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Goku(saiyans)",
  grade: "Bronze",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/m9tieb.jpg",
  Price: "130nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Goku(SSJBlue)",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/00ehxc.jpg",
  Price: "450nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Goku(SSJ4)",
  grade: "Or",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/cz69qw.jpg",
  Price: "350nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Goku(UI)",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/kt9847.jpg",
  Price: "500nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Goku(UIM)",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/u7bja5.jpg",
  Price: "550nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Goku(SSJGod)",
  grade: "Or",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/54ri6n.jpg",
  Price: "420nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gon",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/ry2s2p.jpg",
  Price: "450k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Goten",
  grade: "Argent",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/lstklv.jpg",
  Price: "150nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gotunks",
  grade: "Argent",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/cmwm6d.jpg",
  Price: "280nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gray",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/p0m71h.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Guy(4GG)",
  grade: "Argent",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/ydickg.jpg",
  Price: "600k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gyokko",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/z5ma7e.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gyomei",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/2zgiik.jpg",
  Price: "400k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gyotaro",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/iefaij.jpg",
  Price: "150k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
}, 
{
  name: "Hades",
  grade: "Or",
  category: "SSP",
  images: "",
  card: "https://files.catbox.moe/12yij9.jpg",
  Price: "500nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Hakari",
  grade: "Bronze",
  category: "Ultra SP",
  images: "",
  card: "https://files.catbox.moe/2k6dyk.jpg",
  Price: "400K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Haku",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/iqzqpd.jpg",
  Price: "100K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Hanami",
  grade: "Bronze",
  category: "Sparking SP",
  images: "",
  card: "https://files.catbox.moe/s8ajn1.jpg",
  Price: "400K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Hanzo",
  grade: "Argent",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/bfepmy.jpg",
  Price: "500K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Haruta",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/plkxqq.jpg",
  Price: "100K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Hashirama(Alive)",
  grade: "Argent",
  category: "Legend SP",
  images: "",
  card: "https://files.catbox.moe/vom5wp.jpg",
  Price: "1M300K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Hashirama(Edo)",
  grade: "Argent",
  category: "Legend SP",
  images: "",
  card: "https://files.catbox.moe/08zqem.jpg",
  Price: "1M500K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Hawk",
  grade: "Bronze",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/enl424.jpg",
  Price: "400K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Hidan",
  grade: "Bronze",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/896un5.jpg",
  Price: "300K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Higuruma",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/e3cqou.jpg",
  Price: "150K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Hinata",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/l7bwxg.jpg",
  Price: "100K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Hiruzen",
  grade: "Argent",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/e15qos.jpg",
  Price: "600K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Hisoka",
  grade: "Bronze",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/z2ku4m.jpg",
  Price: "300K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Hit",
  grade: "Or",
  category: "Ultra SSP",
  images: "",
  card: "https://files.catbox.moe/3t3uzr.jpg",
  Price: "430nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "HommeMasqué",
  grade: "Argent",
  category: "Legend SM",
  images: "",
  card: "https://files.catbox.moe/sccdyw.jpg",
  Price: "600K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Hyoga",
  grade: "Argent",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/eqbudy.jpg",
  Price: "500K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Hypnos",
  grade: "Or",
  category: "Legend SSP",
  images: "",
  card: "https://files.catbox.moe/9k7vjk.jpg",
  Price: "400nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
  {
  name: "Sukuna(4F)",
  grade: "Bronze",
  category: "Legend SP",
  images: "",
  card: "https://files.catbox.moe/bozoos.jpg",
  Price: "50nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Sukuna(19F)",
  grade: "Argent",
  category: "Legend SP",
  images: "",
  card: "https://files.catbox.moe/4v8ltt.jpg",
  Price: "100nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Sukuna(Shibuya)",
  grade: "Argent",
  category: "Legend S",
  images: "",
  card: "https://files.catbox.moe/ayhiwq.jpg",
  Price: "800K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Sukuna(Heian)",
  grade: "Argent",
  category: "Legend SP",
  images: "",
  card: "https://files.catbox.moe/cio9my.jpg",
  Price: "100nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Ikki",
  grade: "Argent",
  category: "Ultra SP",
  images: "",
  card: "https://files.catbox.moe/5s7uwj.jpg",
  Price: "950K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Ino",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/0spc1o.jpg",
  Price: "100K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Ino(JJK)",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/cg2wxw.jpg",
  Price: "100K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Inojin",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/23wvgt.jpg",
  Price: "100K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Inosuke",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/8zmkr0.jpg",
  Price: "100K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Ishiki",
  grade: "Or",
  category: "Legend SP",
  images: "",
  card: "https://files.catbox.moe/m6vjmz.jpg",
  Price: "2M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Itachi",
  grade: "Argent",
  category: "Legend SM",
  images: "",
  card: "https://files.catbox.moe/f0nd4b.jpg",
  Price: "600K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Itachi(Edo)",
  grade: "Argent",
  category: "Ultra S",
  images: "",
  card: "https://files.catbox.moe/xpzn76.jpg",
  Price: "700K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "JackTheRipper",
  grade: "Argent",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/f78k47.jpg",
  Price: "500K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Janemba",
  grade: "Or",
  category: "Ultra SSP",
  images: "",
  card: "https://files.catbox.moe/90dppi.jpg",
  Price: "300nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Jeece",
  grade: "Bronze",
  category: "Sparking SSP",
  images: "",
  card: "https://files.catbox.moe/razec6.jpg",
  Price: "90nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Jellal",
  grade: "Argent",
  category: "Ultra SM",
  images: "",
  card: "https://files.catbox.moe/ru57o0.jpg",
  Price: "550K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Jigen",
  grade: "Or",
  category: "Legend S",
  images: "",
  card: "https://files.catbox.moe/mwdvg4.jpg",
  Price: "1M500K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Jimbei",
  grade: "Bronze",
  category: "Sparking SP",
  images: "",
  card: "https://files.catbox.moe/fmwot7.jpg",
  Price: "400K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Jiraya",
  grade: "Bronze",
  category: "Ultra SP",
  images: "",
  card: "https://files.catbox.moe/2gijaq.jpg",
  Price: "450K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Jiren",
  grade: "Or",
  category: "Legend SSP",
  images: "",
  card: "https://files.catbox.moe/ox8j94.jpg",
  Price: "550nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Jogo",
  grade: "Argent",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/ul7qbm.jpg",
  Price: "500K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Jotaro",
  grade: "Argent",
  category: "Legend SM",
  images: "",
  card: "https://files.catbox.moe/3axyi1.jpg",
  Price: "800K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Jugo",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/fw3z6n.jpg",
  Price: "100K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
