const cards = [
{
  name: "3rdRaikage",
  grade: "Argent",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/7c3pgw.jpg",
  Price: "800K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "A",
  grade: "Argent",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/amfh8w.jpg",
  Price: "600K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Ace",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/5vqryh.jpg",
  Price: "400K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Acnologia",
  grade: "Or",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/dy20sv.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Aiolia",
  grade: "Or",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/2mbwpb.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Akainu",
  grade: "Argent",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/qgrflk.jpg",
  Price: "800K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Akaza",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/o8waf7.jpg",
  Price: "450K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Aldebaran",
  grade: "Or",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/nvdw2s.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "AllForOne",
  grade: "Or",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/u18ovi.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "AllMight",
  grade: "Or",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/3x7bn9.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
}, 
{
  name: "Android16",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/tt79m2.jpg",
  Price: "100nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Android17(Dbz)",
  grade: "Argent",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/hohfci.jpg",
  Price: "200nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Android17(Dbs)",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/4bl67g.jpg",
  Price: "420nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Android18",
  grade: "Argent",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/b7neim.jpg",
  Price: "190nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Android19",
  grade: "Bronze",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/1lao5m.jpg",
  Price: "90nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Aoi",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/0rocs7.jpg",
  Price: "350k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Aokiji",
  grade: "Argent",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/dhy54u.jpg",
  Price: "800k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Aphrodite",
  grade: "Or",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/fairbf.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Asta",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/tjsj81.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Asta(Arc2)",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/2cd5ht.jpg",
  Price: "450k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Asuma",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/e9h4s7.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "AtomicSamurai",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/ihy73q.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Avdol",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/wgv1t5.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "BabyVegeta",
  grade: "Or",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/ahxz48.jpg",
  Price: "310nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Bakugo",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/gz77gh.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Bardock",
  grade: "Bronze",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/pidi5o.jpg",
  Price: "110nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Bang",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/yis1od.jpg",
  Price: "450k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Beerus",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/y9cgpo.jpg",
  Price: "530nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Bigmom",
  grade: "Argent",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/8qo8yi.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "BlackGoku",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/un7c3l.jpg",
  Price: "460nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Blizzard",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/q3qznx.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Bojack",
  grade: "Argent",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/ck3vpk.jpg",
  Price: "120nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Boro",
  grade: "Argent",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/bokgxn.jpg",
  Price: "700k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Boros",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/ofoqc5.jpg",
  Price: "2M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Borushiki",
  grade: "Argent",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/ayb8n5.jpg",
  Price: "800k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Boruto",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/8qzmzr.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Broly",
  grade: "Argent",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/au0pd6.jpg",
  Price: "300nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Broly(Dbs)",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/2qvkfx.jpg",
  Price: "480nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Brooks",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/kf359g.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Buhan",
  grade: "Or",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/2tbn9y.jpg",
  Price: "340nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Burter",
  grade: "Bronze",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/jkx88l.jpg",
  Price: "90nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Buu(super)",
  grade: "Or",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/5lfqpz.jpg",
  Price: "310nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Buu(Fat)",
  grade: "Or",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/xnl4el.jpg",
  Price: "300nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Buu(Kid)",
  grade: "Or",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/bb2e50.jpg",
  Price: "360nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Buutenks",
  grade: "Or",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/1gcugi.jpg",
  Price: "320nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
}, 
  {
  name: "Cabba",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/rkdbjj.jpg",
  Price: "130nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Caufila",
  grade: "Argent",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/36yixr.jpg",
  Price: "200nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Cell(perfect)",
  grade: "Argent",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/3vv40w.jpg",
  Price: "280nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Cell(super)",
  grade: "Argent",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/6mi2yw.jpg",
  Price: "210nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Cell(base)",
  grade: "Bronze",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/xsh1ot.jpg",
  Price: "100nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Chiyo",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/5m69a3.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Choji",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/caghzt.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Choso",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/ww982g.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Chrollo",
  grade: "Argent",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/jpuv9q.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Code",
  grade: "Argent",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/bhq7oh.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Code(TBV)",
  grade: "Or",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/3vhh0l.jpg",
  Price: "1m200k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Crocodile",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/s8yttz.jpg",
  Price: "400k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Dabi",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/mjb4lj.jpg",
  Price: "400k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Dabura",
  grade: "Argent",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/edan2e.jpg",
  Price: "250nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Daemon",
  grade: "Or",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/s0sucf.jpg",
  Price: "1m800k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Dagon",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/cp5op5.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Daki",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/14j5af.jpg",
  Price: "150k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Dante",
  grade: "Or",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/n4dlb1.jpg",
  Price: "1m",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Danzo",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/jve2vt.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Darui",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/zs80ob.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Deathmask",
  grade: "Or",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/m6zwzi.jpg",
  Price: "1m500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "DeepSeaKing",
  grade: "Argent",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/yqiviz.jpg",
  Price: "700k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Deepa",
  grade: "Argent",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/epjakr.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Deidara",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/m0wm1s.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "DekuRogueHero",
  grade: "Argent",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/z5hzqb.jpg",
  Price: "700k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Deku",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/oh99hl.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Delta",
  grade: "Argent",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/h68hzb.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Denki",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/xerqh0.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Diavolo",
  grade: "Argent",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/yw5xb8.jpg",
  Price: "900k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Dio",
  grade: "Argent",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/32pw7w.jpg",
  Price: "900k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Doflamingo",
  grade: "Argent",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/v126vu.jpg",
  Price: "550k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Doma",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/4xdikn.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Dr.Gero",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/glg41l.jpg",
  Price: "600k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Dyspo",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/tr27u0.jpg",
  Price: "400nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Edward",
  grade: "Argent",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/q5bapo.jpg",
  Price: "1m200k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Eida",
  grade: "Or",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/5tx64p.jpg",
  Price: "1m800k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Eijiro",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/ljz7bk.jpg.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Endeavor",
  grade: "Argent",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/qcunun.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Enmu",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/x4hsa6.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Erza",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/otsr2e.jpg",
  Price: "450k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
}, 
{
  name: "FlashyFlash",
  grade: "Argent",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/git5xh.jpg",
  Price: "700k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Franky",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/t46wfj.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Frieza(super)",
  grade: "Argent",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/l97ml8.jpg",
  Price: "160nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Frieza(Base)",
  grade: "Bronze",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/i84paz.jpg",
  Price: "150nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Frieza(Golden)",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/dptorv.jpg",
  Price: "420nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Fuegoleon",
  grade: "Argent",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/2ocv94.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Fujitora",
  grade: "Argent",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/fslosy.jpg",
  Price: "700k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Fumikage",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/mucucs.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gaara(4GG)",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/v3nvkj.jpg",
  Price: "400k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gaara",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/cto2vg.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gajeel",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/8j1xus.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Garou",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/hbdp8l.jpg",
  Price: "450k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "GarouMonster",
  grade: "Argent",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/joebj6.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Garou(cosmic)",
  grade: "Or",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/6qyvrq.jpg",
  Price: "200nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Garp",
  grade: "Argent",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/20h2tl.jpg",
  Price: "800k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gauche",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/7gv4r9.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gengetsu",
  grade: "Argent",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/77h87l.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Genos(forme 2)",
  grade: "Argent",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/0p7zf7.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Genos",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/yvk9j3.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Geto",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/ytx8vy.jpg",
  Price: "400k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Geto(student)",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/0o4is7.jpg",
  Price: "350k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gildarts",
  grade: "Argent",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/41g7x4.jpg",
  Price: "900k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Ginyu",
  grade: "Bronze",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/1nhx0y.jpg",
  Price: "100nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Giorno",
  grade: "Or",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/5wvjc1.jpg",
  Price: "1m200k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Giyu",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/7ehtyz.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gogeta(Dbz)",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/ddf764.jpg",
  Price: "450nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gogeta(Dbs)",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/ru0r9d.jpg",
  Price: "550nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gogeta(SSJ4)",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/agk0gp.jpg",
  Price: "460nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gohan(Beast)",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/aj97ba.jpg",
  Price: "550nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gohan(Futur)",
  grade: "Argent",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/ghl7so.jpg",
  Price: "190nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gohan(SSj2)",
  grade: "Argent",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/ym9696.jpg",
  Price: "290nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gohan(SSJ)",
  grade: "Argent",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/d39zp8.jpg",
  Price: "150nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gohan(Buu arc)",
  grade: "Argent",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/r3za80.jpg",
  Price: "260nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gohan(Kid)",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/3b7ypn.jpg",
  Price: "90nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gohan(ultime)",
  grade: "Or",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/arcs79.jpg",
  Price: "350nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gohan(Dbs)",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/gfnu6y.jpg",
  Price: "430nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gojo",
  grade: "Argent",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/3hmg8k.jpg",
  Price: "800k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gojo(shinjuku)",
  grade: "Argent",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/jg1bvq.jpg",
  Price: "100nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gojo(Student)",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/qnha9o.jpg",
  Price: "50nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Goku(SSJnamek)",
  grade: "Argent",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/l4lt5w.jpg",
  Price: "180nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Goku(androids)",
  grade: "Argent",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/fpkm2x.jpg",
  Price: "270nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Goku(SSJ2)",
  grade: "Argent",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/0ib3ua.jpg",
  Price: "290nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Goku(name)",
  grade: "Bronze",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/vp7t7k.jpg",
  Price: "150nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Goku(debut)",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/bxvdah.jpg",
  Price: "100nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Goku(saiyans)",
  grade: "Bronze",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/m9tieb.jpg",
  Price: "130nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Goku(SSJBlue)",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/00ehxc.jpg",
  Price: "450nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Goku(SSJ4)",
  grade: "Or",
  category: "SS",
  images: "",
  card: "https://files.catbox.moe/cz69qw.jpg",
  Price: "350nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Goku(UI)",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/kt9847.jpg",
  Price: "500nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Goku(UIM)",
  grade: "Or",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/u7bja5.jpg",
  Price: "550nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Goku(SSJGod)",
  grade: "Or",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/54ri6n.jpg",
  Price: "420nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gon",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/ry2s2p.jpg",
  Price: "450k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Goten",
  grade: "Argent",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/lstklv.jpg",
  Price: "150nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gotunks",
  grade: "Argent",
  category: "SS+",
  images: "",
  card: "https://files.catbox.moe/cmwm6d.jpg",
  Price: "280nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gray",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/p0m71h.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Guy(4GG)",
  grade: "Argent",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/ydickg.jpg",
  Price: "600k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gyokko",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/z5ma7e.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gyomei",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/2zgiik.jpg",
  Price: "400k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Gyotaro",
  grade: "Bronze",
  category: "S-",
  images: "",
  card: "https://files.catbox.moe/iefaij.jpg",
  Price: "150k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
}, 
{
  name: "Hades",
  grade: "Or",
  category: "SSP",
  images: "",
  card: "https://files.catbox.moe/12yij9.jpg",
  Price: "500nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Hakari",
  grade: "Bronze",
  category: "Ultra SP",
  images: "",
  card: "https://files.catbox.moe/2k6dyk.jpg",
  Price: "400K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Haku",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/iqzqpd.jpg",
  Price: "100K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Hanami",
  grade: "Bronze",
  category: "Sparking SP",
  images: "",
  card: "https://files.catbox.moe/s8ajn1.jpg",
  Price: "400K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Hanzo",
  grade: "Argent",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/bfepmy.jpg",
  Price: "500K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Haruta",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/plkxqq.jpg",
  Price: "100K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Hashirama(Alive)",
  grade: "Argent",
  category: "Legend SP",
  images: "",
  card: "https://files.catbox.moe/vom5wp.jpg",
  Price: "1M300K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Hashirama(Edo)",
  grade: "Argent",
  category: "Legend SP",
  images: "",
  card: "https://files.catbox.moe/08zqem.jpg",
  Price: "1M500K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Hawk",
  grade: "Bronze",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/enl424.jpg",
  Price: "400K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Hidan",
  grade: "Bronze",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/896un5.jpg",
  Price: "300K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Higuruma",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/e3cqou.jpg",
  Price: "150K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Hinata",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/l7bwxg.jpg",
  Price: "100K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Hiruzen",
  grade: "Argent",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/e15qos.jpg",
  Price: "600K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Hisoka",
  grade: "Bronze",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/z2ku4m.jpg",
  Price: "300K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Hit",
  grade: "Or",
  category: "Ultra SSP",
  images: "",
  card: "https://files.catbox.moe/3t3uzr.jpg",
  Price: "430nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "HommeMasqué",
  grade: "Argent",
  category: "Legend SM",
  images: "",
  card: "https://files.catbox.moe/sccdyw.jpg",
  Price: "600K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Hyoga",
  grade: "Argent",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/eqbudy.jpg",
  Price: "500K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Hypnos",
  grade: "Or",
  category: "Legend SSP",
  images: "",
  card: "https://files.catbox.moe/9k7vjk.jpg",
  Price: "400nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
  {
  name: "Sukuna(4F)",
  grade: "Bronze",
  category: "Legend SP",
  images: "",
  card: "https://files.catbox.moe/bozoos.jpg",
  Price: "50nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Sukuna(19F)",
  grade: "Argent",
  category: "Legend SP",
  images: "",
  card: "https://files.catbox.moe/4v8ltt.jpg",
  Price: "100nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Sukuna(Shibuya)",
  grade: "Argent",
  category: "Legend S",
  images: "",
  card: "https://files.catbox.moe/ayhiwq.jpg",
  Price: "800K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Sukuna(Heian)",
  grade: "Argent",
  category: "Legend SP",
  images: "",
  card: "https://files.catbox.moe/cio9my.jpg",
  Price: "100nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Ikki",
  grade: "Argent",
  category: "Ultra SP",
  images: "",
  card: "https://files.catbox.moe/5s7uwj.jpg",
  Price: "950K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Ino",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/0spc1o.jpg",
  Price: "100K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Ino(JJK)",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/cg2wxw.jpg",
  Price: "100K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Inojin",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/23wvgt.jpg",
  Price: "100K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Inosuke",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/8zmkr0.jpg",
  Price: "100K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Ishiki",
  grade: "Or",
  category: "Legend SP",
  images: "",
  card: "https://files.catbox.moe/m6vjmz.jpg",
  Price: "2M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Itachi",
  grade: "Argent",
  category: "Legend SM",
  images: "",
  card: "https://files.catbox.moe/f0nd4b.jpg",
  Price: "600K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Itachi(Edo)",
  grade: "Argent",
  category: "Ultra S",
  images: "",
  card: "https://files.catbox.moe/xpzn76.jpg",
  Price: "700K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "JackTheRipper",
  grade: "Argent",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/f78k47.jpg",
  Price: "500K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Janemba",
  grade: "Or",
  category: "Ultra SSP",
  images: "",
  card: "https://files.catbox.moe/90dppi.jpg",
  Price: "300nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Jeece",
  grade: "Bronze",
  category: "Sparking SSP",
  images: "",
  card: "https://files.catbox.moe/razec6.jpg",
  Price: "90nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Jellal",
  grade: "Argent",
  category: "Ultra SM",
  images: "",
  card: "https://files.catbox.moe/ru57o0.jpg",
  Price: "550K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Jigen",
  grade: "Or",
  category: "Legend S",
  images: "",
  card: "https://files.catbox.moe/mwdvg4.jpg",
  Price: "1M500K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Jimbei",
  grade: "Bronze",
  category: "Sparking SP",
  images: "",
  card: "https://files.catbox.moe/fmwot7.jpg",
  Price: "400K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Jiraya",
  grade: "Bronze",
  category: "Ultra SP",
  images: "",
  card: "https://files.catbox.moe/2gijaq.jpg",
  Price: "450K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Jiren",
  grade: "Or",
  category: "Legend SSP",
  images: "",
  card: "https://files.catbox.moe/ox8j94.jpg",
  Price: "550nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Jogo",
  grade: "Argent",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/ul7qbm.jpg",
  Price: "500K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Jotaro",
  grade: "Argent",
  category: "Legend SM",
  images: "",
  card: "https://files.catbox.moe/3axyi1.jpg",
  Price: "800K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Jugo",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/fw3z6n.jpg",
  Price: "100K",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Julius",
  grade: "Or",
  category: "Legend S",
  images: "",
  card: "https://files.catbox.moe/r51fdi.jpg",
  Price: "1M500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Kabuto(Ermite)",
  grade: "Argent",
  category: "Legend S",
  images: "",
  card: "https://files.catbox.moe/71wcyi.jpg",
  Price: "800k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Kabuto",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/0entih.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Kaguya",
  grade: "Or",
  category: "Legend SP",
  images: "",
  card: "https://files.catbox.moe/09aavm.jpg",
  Price: "2M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Kaido",
  grade: "Argent",
  category: "Legend SP",
  images: "",
  card: "https://files.catbox.moe/jpfezg.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Kaigaku",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/fx8882.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Kakashi(4GG)",
  grade: "Argent",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/v15u2p.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Kakashi(Ado)",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/yht6x6.jpg",
  Price: "150k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Kakashi",
  grade: "Bronze",
  category: "Ultra SP",
  images: "",
  card: "https://files.catbox.moe/cd4vqa.jpg",
  Price: "400k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Kakuzu",
  grade: "Bronze",
  category: "Ultra SP",
  images: "",
  card: "https://files.catbox.moe/u0srbo.jpg",
  Price: "400k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Kakyoin",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/gq9ncc.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Kale",
  grade: "Argent",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/rf7tpo.jpg",
  Price: "280nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Kamo",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/ux5uaa.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Kanao",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/zfk7bs.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Kankuro",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/qezt29.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Kashimo",
  grade: "Argent",
  category: "Ultra SM",
  images: "",
  card: "https://files.catbox.moe/nwl69h.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Kashin",
  grade: "Argent",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/s60eyv.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Katakuri",
  grade: "Argent",
  category: "Ultra S",
  images: "",
  card: "https://files.catbox.moe/w1ai58.jpg",
  Price: "800k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Kawaki",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/wo4hxm.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Kawashiki",
  grade: "Argent",
  category: "Legende SP",
  images: "",
  card: "https://files.catbox.moe/2equyh.jpg",
  Price: "800k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
  }, 
  {
  name: "Kefla",
  grade: "Or",
  category: "Ultra SSP",
  images: "",
  card: "https://files.catbox.moe/lg1241.jpg",
  Price: "480nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Kenjaku",
  grade: "Argent",
  category: "Ultra SM",
  images: "",
  card: "https://files.catbox.moe/4fph85.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Kiba",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/i9utly.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Kid",
  grade: "Bronze",
  category: "Ultra SP",
  images: "",
  card: "https://files.catbox.moe/uli7li.jpg",
  Price: "450k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Killerbee",
  grade: "Argent",
  category: "Ultra SM",
  images: "",
  card: "https://files.catbox.moe/rt3jgx.jpg",
  Price: "600k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Kilua",
  grade: "Argent",
  category: "Ultra SM",
  images: "",
  card: "https://files.catbox.moe/v9gws9.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Kimimaro",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/1z659k.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Kisame",
  grade: "Argent",
  category: "Ultra SM",
  images: "",
  card: "https://files.catbox.moe/86r0s0.jpg",
  Price: "600k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Kizaru",
  grade: "Or",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/tffpmi.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Kokushibo",
  grade: "Argent",
  category: "Legend SM",
  images: "",
  card: "https://files.catbox.moe/c4upfm.jpg",
  Price: "50nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Konan",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/xiw3r5.jpg",
  Price: "200k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Konohamaru",
  grade: "Bronze",
  category: "S+",
  images: "",
  card: "https://files.catbox.moe/gkkvrj.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Krillin",
  grade: "Bronze",
  category: "Sparking SP",
  images: "",
  card: "https://files.catbox.moe/zvmx6x.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Kurapika",
  grade: "Bronze",
  category: "Ultra S",
  images: "",
  card: "https://files.catbox.moe/xtjdm3.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Kusakabe",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/i5iqnv.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Langris",
  grade: "Bronze",
  category: "Ultra S",
  images: "",
  card: "https://files.catbox.moe/69ld8o.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Larue",
  grade: "Bronze",
  category: "S",
  images: "",
  card: "https://files.catbox.moe/uwo4at.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Law",
  grade: "Bronze",
  category: "Ultra S",
  images: "",
  card: "https://files.catbox.moe/j60re6.jpg",
  Price: "350k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Laxus",
  grade: "Argent",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/c1znw5.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
}, 
 {
  name: "Laxus",
  grade: "Argent",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/c1znw5.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Lee",
  grade: "Bronze",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/m2r782.jpg",
  Price: "150k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Lemilion",
  grade: "Bronze",
  category: "Sparking SP",
  images: "",
  card: "https://files.catbox.moe/d72cbu.jpg",
  Price: "400k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Leopold",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/qd65jc.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Licht",
  grade: "Or",
  category: "Legend SP",
  images: "",
  card: "https://files.catbox.moe/y9fz3u.jpg",
  Price: "2m",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Luck",
  grade: "Bronze",
  category: "Ultra S",
  images: "",
  card: "https://files.catbox.moe/ggy08x.jpg",
  Price: "350k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Lucy",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/h05aul.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Luffy (Wano)",
  grade: "Argent",
  category: "Legend S",
  images: "",
  card: "https://files.catbox.moe/0mfgst.jpg",
  Price: "1m",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Luffy",
  grade: "Argent",
  category: "Ultra SM",
  images: "",
  card: "https://files.catbox.moe/o18qti.jpg",
  Price: "600k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Lyon",
  grade: "Bronze",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/b0iaqz.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Madara (Orange)",
  grade: "Argent",
  category: "Legend SM",
  images: "",
  card: "https://files.catbox.moe/0ssw7d.jpg",
  Price: "600k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Madara (Edo)",
  grade: "Argent",
  category: "Legend SP",
  images: "",
  card: "https://files.catbox.moe/unrace.jpg",
  Price: "1m",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Madara (Alive)",
  grade: "Argent",
  category: "Legend SP",
  images: "",
  card: "https://files.catbox.moe/bpyee5.jpg",
  Price: "1m",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Madara (Rebirth)",
  grade: "Argent",
  category: "Legend SP",
  images: "",
  card: "https://files.catbox.moe/fr7lei.jpg",
  Price: "1m500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Madara (Rinnegan)",
  grade: "Argent",
  category: "Sparking SP",
  images: "",
  card: "https://files.catbox.moe/thy0dm.jpg",
  Price: "1m",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Madara (Rikudo)",
  grade: "Or",
  category: "Legend S",
  images: "",
  card: "https://files.catbox.moe/zl2zrk.jpg",
  Price: "1m500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Magna",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/xcel78.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Mahito",
  grade: "Bronze",
  category: "Ultra SM",
  images: "",
  card: "https://files.catbox.moe/0dakux.jpg",
  Price: "350k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Mahito (Shibuya)",
  grade: "Bronze",
  category: "Ultra SP",
  images: "",
  card: "https://files.catbox.moe/acd49z.jpg",
  Price: "400k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Mahoraga",
  grade: "Argent",
  category: "Legend SM",
  images: "",
  card: "https://files.catbox.moe/3qr43l.jpg",
  Price: "1m",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Mai",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/ok2814.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
}, 
 {
  name: "Vegeta (Majin)",
  grade: "Argent",
  category: "Legend SSP",
  images: "",
  card: "https://files.catbox.moe/rhx9q4.jpg",
  Price: "290nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Maki (CG)",
  grade: "Argent",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/xx854g.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Maki",
  grade: "Bronze",
  category: "Ultra S",
  images: "",
  card: "https://files.catbox.moe/qi8e10.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Mechamaru",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/z0kfu2.jpg",
  Price: "150k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Megumi",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/91fz38.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Mei Terumi",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/kmdiht.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Mereleona",
  grade: "Argent",
  category: "Ultra SM",
  images: "",
  card: "https://files.catbox.moe/044xjy.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Meruem",
  grade: "Argent",
  category: "Legend SP",
  images: "",
  card: "https://files.catbox.moe/h1bm0w.jpg",
  Price: "1m",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Metal Bat",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/80fves.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Metal Lee",
  grade: "Bronze",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/zq8yyk.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Mifune",
  grade: "Bronze",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/3xj4g8.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Miguel",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/s0vkwy.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Mihawk",
  grade: "Argent",
  category: "Legend SP",
  images: "",
  card: "https://files.catbox.moe/u89pdl.jpg",
  Price: "1m",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Minato (Edo)",
  grade: "Argent",
  category: "Legend S",
  images: "",
  card: "https://files.catbox.moe/mk0mgp.jpg",
  Price: "800k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Minato",
  grade: "Argent",
  category: "Legend SM",
  images: "",
  card: "https://files.catbox.moe/q1yx82.jpg",
  Price: "600k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Minos",
  grade: "Or",
  category: "Sparking SP",
  images: "",
  card: "https://files.catbox.moe/lmkfw4.jpg",
  Price: "2m",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Mirko",
  grade: "Bronze",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/idg38s.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Mitsuki",
  grade: "Bronze",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/bktfvo.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Mitsuri",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/v5jnkh.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Miwa",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/d15c8f.jpg",
  Price: "1000k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Momo",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/9ckqpa.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Momo (JJK)",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/x6ozts.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Momoshiki",
  grade: "Or",
  category: "Ultra SM",
  images: "",
  card: "https://files.catbox.moe/75hgce.jpg",
  Price: "1M200k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Mr. Satan",
  grade: "Bronze",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/xkqt0d.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Muichiro",
  grade: "Bronze",
  category: "Ultra SP",
  images: "",
  card: "https://files.catbox.moe/fcnlkr.jpg",
  Price: "400k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Muu",
  grade: "Argent",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/xn5cvq.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Muzan",
  grade: "Argent",
  category: "Legend SMM",
  images: "",
  card: "https://files.catbox.moe/sv01h1.jpg",
  Price: "50nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Mû",
  grade: "Or",
  category: "Legende SM",
  images: "",
  card: "https://files.catbox.moe/wuart5.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
  }, 
  {
  name: "Nacht",
  grade: "Bronze",
  category: "Ultra SP",
  images: "",
  card: "https://files.catbox.moe/wthf8r.jpg",
  Price: "400k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Nagato",
  grade: "Argent",
  category: "Legend S",
  images: "",
  card: "https://files.catbox.moe/9jvgu8.jpg",
  Price: "800k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Nami",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/eu6rue.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Nanami",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/exv4zk.jpg",
  Price: "150k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Naobito",
  grade: "Bronze",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/i9277v.jpg",
  Price: "250k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Naoya",
  grade: "Bronze",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/svc0q3.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Nappa",
  grade: "Bronze",
  category: "Sparking SS",
  images: "",
  card: "https://files.catbox.moe/tg5ffy.jpg",
  Price: "120nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Naruto (KCM)",
  grade: "Argent",
  category: "Legend S",
  images: "",
  card: "https://files.catbox.moe/j57927.jpg",
  Price: "800k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Naruto (KCM2)",
  grade: "Argent",
  category: "Legend SP",
  images: "",
  card: "https://files.catbox.moe/lqpn2n.jpg",
  Price: "900k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Naruto (Ermite)",
  grade: "Argent",
  category: "Ultra SM",
  images: "",
  card: "https://files.catbox.moe/1rr1dk.jpg",
  Price: "550k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Naruto",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/8qof2k.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Naruto (The Last)",
  grade: "Or",
  category: "Legend SM",
  images: "",
  card: "https://files.catbox.moe/u0y0kf.jpg",
  Price: "1m300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Naruto (SP)",
  grade: "Or",
  category: "Legend SM",
  images: "",
  card: "https://files.catbox.moe/dj0ex3.jpg",
  Price: "1m500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Naruto (Hokage)",
  grade: "Or",
  category: "Legend SM",
  images: "",
  card: "https://files.catbox.moe/372cj1.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Natsu",
  grade: "Argent",
  category: "Ultra SM",
  images: "",
  card: "https://files.catbox.moe/l2gp0d.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Neji",
  grade: "Bronze",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/gtbyyb.jpg",
  Price: "150k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Nejire",
  grade: "Bronze",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/hjestn.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Netero",
  grade: "Argent",
  category: "Ultra S",
  images: "",
  card: "https://files.catbox.moe/qm6ts0.jpg",
  Price: "700k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Nezuko",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/o2oqnp.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Nobara",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/umse5q.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Noelle",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/3hn8s1.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Nozel",
  grade: "Argent",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/t1c2xd.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
  }, 
  {
  name: "Obanai",
  grade: "Bronze",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/dm3gua.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Obito (4GG)",
  grade: "Argent",
  category: "Legend S",
  images: "",
  card: "https://files.catbox.moe/qqf4kv.jpg",
  Price: "800k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Obito (Ado)",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/fpmsiz.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Obito (Rage)",
  grade: "Bronze",
  category: "Ultra SP",
  images: "",
  card: "https://files.catbox.moe/papag1.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Obito (Rikudo)",
  grade: "Or",
  category: "Legend SM",
  images: "",
  card: "https://files.catbox.moe/czuvpu.jpg",
  Price: "1m",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Ochaco",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/ps1o9h.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Omega Shenron",
  grade: "Or",
  category: "Ultra SSP",
  images: "",
  card: "https://files.catbox.moe/f2s078.jpg",
  Price: "400nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Onoki",
  grade: "Bronze",
  category: "Legend SP",
  images: "",
  card: "https://files.catbox.moe/wm3pdr.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Orochimaru",
  grade: "Bronze",
  category: "Ultra SP",
  images: "",
  card: "https://files.catbox.moe/h5il4v.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Overhaul",
  grade: "Bronze",
  category: "Ultra SP",
  images: "",
  card: "https://files.catbox.moe/bfmk4u.jpg",
  Price: "450k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Pain",
  grade: "Argent",
  category: "Ultra SM",
  images: "",
  card: "https://files.catbox.moe/mjxjao.jpg",
  Price: "700k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Panda",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/lqbo0t.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Patolli",
  grade: "Or",
  category: "Ultra SM",
  images: "",
  card: "https://files.catbox.moe/kapj43.jpg",
  Price: "1m",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Pegasus",
  grade: "Or",
  category: "Legend SSP",
  images: "",
  card: "https://files.catbox.moe/1353bb.jpg",
  Price: "500nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Piccolo (Fusion)",
  grade: "Argent",
  category: "Ultra SS",
  images: "",
  card: "https://files.catbox.moe/z17dbx.jpg",
  Price: "200nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Piccolo",
  grade: "Bronze",
  category: "Sparking SSM",
  images: "",
  card: "https://files.catbox.moe/vmzg90.jpg",
  Price: "100nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Polnareff",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/xha2ko.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Pucci",
  grade: "Argent",
  category: "Legend SM",
  images: "",
  card: "https://files.catbox.moe/61eiyg.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
    }, 
  {
  name: "Raccoon",
  grade: "Bronze",
  category: "Sparking SSP",
  images: "",
  card: "https://files.catbox.moe/saiqjf.jpg",
  Price: "90nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Radamanthys",
  grade: "Or",
  category: "Sparking SP",
  images: "",
  card: "https://files.catbox.moe/dk68wa.jpg",
  Price: "1M500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Raditz",
  grade: "Bronze",
  category: "Sparking SSM",
  images: "",
  card: "https://files.catbox.moe/r1ltde.jpg",
  Price: "110nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Rengoku",
  grade: "Bronze",
  category: "Ultra S",
  images: "",
  card: "https://files.catbox.moe/tv23rh.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Rhya",
  grade: "Argent",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/ok93zn.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Robin",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/du8m3n.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Rogue",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/yofjr9.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Rui",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/y1uty1.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Ryu",
  grade: "Argent",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/gjbi4u.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Sabo",
  grade: "Argent",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/38qeen.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Saga",
  grade: "Or",
  category: "Ultra SP",
  images: "",
  card: "https://files.catbox.moe/1qtha5.jpg",
  Price: "2M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Sai",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/dg8f61.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Saitama",
  grade: "Or",
  category: "Legend SSP",
  images: "",
  card: "https://files.catbox.moe/kskpcn.jpg",
  Price: "300nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Sakura (4GG)",
  grade: "Bronze",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/s64n58.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Sakura",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/a10aqp.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Sanemi",
  grade: "Bronze",
  category: "Ultra S",
  images: "",
  card: "https://files.catbox.moe/nbat3b.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Sanji",
  grade: "Bronze",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/dx9mlf.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Sarada",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/0gmxiu.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Sasori",
  grade: "Bronze",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/230r8w.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Sasuke (EMS)",
  grade: "Argent",
  category: "Legend S",
  images: "",
  card: "https://files.catbox.moe/pia2pc.jpg",
  Price: "800k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Sasuke (Taka)",
  grade: "Argent",
  category: "Ultra SM",
  images: "",
  card: "https://files.catbox.moe/7kbi9l.jpg",
  Price: "600k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Sasuke",
  grade: "Bronze",
  category: "Ultra SP",
  images: "",
  card: "https://files.catbox.moe/1qsskp.jpg",
  Price: "400k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Sasuke (Hebi)",
  grade: "Bronze",
  category: "Ultra SP",
  images: "",
  card: "https://files.catbox.moe/cwaaa7.jpg",
  Price: "450k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Sasuke (Akatsuki)",
  grade: "Bronze",
  category: "Ultra SP",
  images: "",
  card: "https://files.catbox.moe/uxne57.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Sasuke (SP)",
  grade: "Or",
  category: "Legend SM",
  images: "",
  card: "https://files.catbox.moe/7d0flm.jpg",
  Price: "1M200k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Sasuke (Shinden)",
  grade: "Or",
  category: "Legend SM",
  images: "",
  card: "https://files.catbox.moe/haef5r.jpg",
  Price: "1m200k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Sasuke (Boruto)",
  grade: "Or",
  category: "Legend SM",
  images: "",
  card: "https://files.catbox.moe/9bduze.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
  }, 
 {
  name: "Seiya",
  grade: "Argent",
  category: "Ultra S",
  images: "",
  card: "https://files.catbox.moe/epeq5l.jpg",
  Price: "800k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Shaka",
  grade: "Or",
  category: "Legend SM",
  images: "",
  card: "https://files.catbox.moe/ehburs.jpg",
  Price: "2M500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Shanks",
  grade: "Or",
  category: "Legend SM",
  images: "",
  card: "https://files.catbox.moe/17r2x4.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Shigaraki",
  grade: "Argent",
  category: "Ultra S",
  images: "",
  card: "https://files.catbox.moe/jqjscv.jpg",
  Price: "700k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Shikadai",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/fn3b4a.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Shikamaru",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/olrdcv.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Shinki",
  grade: "Bronze",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/iz2ttd.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Shin",
  grade: "Bronze",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/n977zq.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Shino",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/o4izh4.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Shinobu",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/kqej55.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Shinso",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/z5mpoh.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Shiryu",
  grade: "Argent",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/tsh66g.jpg",
  Price: "800k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Shisui",
  grade: "Argent",
  category: "Legend SM",
  images: "",
  card: "https://files.catbox.moe/gdcvd8.jpg",
  Price: "700k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Shoto",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/3cfj4z.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Shun",
  grade: "Argent",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/ndxmd6.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Silva",
  grade: "Bronze",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/p7p2e3.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Sonic",
  grade: "Bronze",
  category: "Sparking SP",
  images: "",
  card: "https://files.catbox.moe/jzy3gr.jpg",
  Price: "400k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Stain",
  grade: "Bronze",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/l7ermt.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Star and Stripes",
  grade: "Argent",
  category: "Ultra S",
  images: "",
  card: "https://files.catbox.moe/blqhww.jpg",
  Price: "100nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Sting",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/t869qh.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Suigetsu",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/1p68ff.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Suiryu",
  grade: "Bronze",
  category: "Sparking SP",
  images: "",
  card: "https://files.catbox.moe/agtxsf.jpg",
  Price: "400k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Super Android 17",
  grade: "Or",
  category: "Legend SSP",
  images: "",
  card: "https://files.catbox.moe/mjnton.jpg",
  Price: "380nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Vegeta (Super)",
  grade: "Argent",
  category: "Legend SSP",
  images: "",
  card: "https://files.catbox.moe/ktvi11.jpg",
  Price: "250nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Susamaru",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/fin05s.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
}, 
  {
  name: "Tanjiro (Demon)",
  grade: "Argent",
  category: "Legend SM",
  images: "",
  card: "https://files.catbox.moe/xlwdvp.jpg",
  Price: "50nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Tanjiro (Début)",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/aq59kx.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Tanjiro",
  grade: "Bronze",
  category: "Ultra S",
  images: "",
  card: "https://files.catbox.moe/y3pnjx.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Tanktop Marcel",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/xxfbj7.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Takako",
  grade: "Argent",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/d1ypx9.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Tatsumaki",
  grade: "Or",
  category: "Legend SM",
  images: "",
  card: "https://files.catbox.moe/4puqzw.jpg",
  Price: "1m",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Teach",
  grade: "Argent",
  category: "Legend SM",
  images: "",
  card: "https://files.catbox.moe/khap3e.jpg",
  Price: "1M",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Temari",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/lvnx8y.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Tengen",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/vg4cyw.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Tenshinhan",
  grade: "Bronze",
  category: "Ultra SP",
  images: "",
  card: "https://files.catbox.moe/binc1i.jpg",
  Price: "600k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Tenten",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/hhl7t4.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Tenya",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/y5u0vt.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Thales",
  grade: "Bronze",
  category: "Sparking SSP",
  images: "",
  card: "https://files.catbox.moe/ljrcbk.jpg",
  Price: "110nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Thanatos",
  grade: "Or",
  category: "Legend SSP",
  images: "",
  card: "https://files.catbox.moe/gycytd.jpg",
  Price: "400nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Tobi (4GG)",
  grade: "Argent",
  category: "Legend S",
  images: "",
  card: "https://files.catbox.moe/yde4i0.jpg",
  Price: "800k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Tobirama",
  grade: "Argent",
  category: "Legend SP",
  images: "",
  card: "https://files.catbox.moe/lomjn4.jpg",
  Price: "900k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Toga",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/pvg87z.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Toge",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/818k07.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Toji",
  grade: "Argent",
  category: "Ultra SM",
  images: "",
  card: "https://files.catbox.moe/mo6e5z.jpg",
  Price: "600k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Toneri",
  grade: "Argent",
  category: "Ultra SP",
  images: "",
  card: "https://files.catbox.moe/nrog1q.jpg",
  Price: "1m",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Toppo",
  grade: "Or",
  category: "Ultra SSP",
  images: "",
  card: "https://files.catbox.moe/fhqr3r.jpg",
  Price: "420nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Trunks (Kid)",
  grade: "Argent",
  category: "Sparking SSM",
  images: "",
  card: "https://files.catbox.moe/ptpckm.jpg",
  Price: "150nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Trunks",
  grade: "Argent",
  category: "Sparking SSM",
  images: "",
  card: "https://files.catbox.moe/alprgr.jpg",
  Price: "200nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Trunks (Futur)",
  grade: "Argent",
  category: "Ultra SSM",
  images: "",
  card: "https://files.catbox.moe/ougnbx.jpg",
  Price: "170nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Trunks (DBS)",
  grade: "Argent",
  category: "Ultra SSP",
  images: "",
  card: "https://files.catbox.moe/zicnsn.jpg",
  Price: "230nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Tsunade",
  grade: "Bronze",
  category: "Ultra S",
  images: "",
  card: "https://files.catbox.moe/nlggb9.jpg",
  Price: "400k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Twice",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/rk9zp5.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
  }, 
  {
  name: "Uraume",
  grade: "Argent",
  category: "Ultra SM",
  images: "",
  card: "https://files.catbox.moe/mugdkc.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Vanessa",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/kyael1.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Vanica",
  grade: "Argent",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/dekzwe.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Vegeta (SSJ)",
  grade: "Argent",
  category: "Ultra SSM",
  images: "",
  card: "https://files.catbox.moe/k2cdjt.jpg",
  Price: "180nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Vegeta (Tracker)",
  grade: "Bronze",
  category: "Sparking SSP",
  images: "",
  card: "https://files.catbox.moe/swz65c.jpg",
  Price: "130nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Vegeta (SSJ4)",
  grade: "Or",
  category: "Legend SS",
  images: "",
  card: "https://files.catbox.moe/fgqu2w.jpg",
  Price: "340nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Vegeta (SSJ Blue)",
  grade: "Or",
  category: "Legend SSP",
  images: "",
  card: "https://files.catbox.moe/l3gss8.jpg",
  Price: "450nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Vegeta (UE)",
  grade: "Or",
  category: "Legend SSP",
  images: "",
  card: "https://files.catbox.moe/b9svgt.jpg",
  Price: "550nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Vegeta (SSJ God)",
  grade: "Or",
  category: "Ultra SSP",
  images: "",
  card: "https://files.catbox.moe/7pznu1.jpg",
  Price: "420nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Vegito (DBZ)",
  grade: "Or",
  category: "Legend SSP",
  images: "",
  card: "https://files.catbox.moe/rgybyi.jpg",
  Price: "450nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Vegito (DBS)",
  grade: "Or",
  category: "Legend SSP",
  images: "",
  card: "https://files.catbox.moe/wujmrs.jpg",
  Price: "550nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Vengeance",
  grade: "Argent",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/aupjwj.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Vetto",
  grade: "Argent",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/xp0i8c.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Victor",
  grade: "Argent",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/m3hq7x.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Videl",
  grade: "Bronze",
  category: "Sparking SP",
  images: "",
  card: "https://files.catbox.moe/0mubo7.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Weather Report",
  grade: "Argent",
  category: "Ultra SM",
  images: "",
  card: "https://files.catbox.moe/eq2wxq.jpg",
  Price: "900k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Wendy",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/uowygv.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Yahaba",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/jqa4l1.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Yamato",
  grade: "Bronze",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/ngy97w.jpg",
  Price: "300k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Yamcha",
  grade: "Bronze",
  category: "Sparking SP",
  images: "",
  card: "https://files.catbox.moe/03fmv6.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Yami",
  grade: "Argent",
  category: "Legend S",
  images: "",
  card: "https://files.catbox.moe/alpzdx.jpg",
  Price: "50nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Yorozu",
  grade: "Argent",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/zydytg.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Yuji (Shibuya)",
  grade: "Bronze",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/w0j4ll.jpg",
  Price: "200k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Yuji (CG)",
  grade: "Argent",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/q3yidh.jpg",
  Price: "50nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Yuji",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/dh6evb.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Yuki",
  grade: "Argent",
  category: "Ultra SM",
  images: "",
  card: "https://files.catbox.moe/16a2yx.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Yuno",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/v3bnlo.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Yuta",
  grade: "Bronze",
  category: "Legend SP",
  images: "",
  card: "https://files.catbox.moe/06fvgx.jpg",
  Price: "400k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Yuta (CG)",
  grade: "Argent",
  category: "Ultra SM",
  images: "",
  card: "https://files.catbox.moe/pm6ioo.jpg",
  Price: "50nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
}, 
  {
  name: "Zabuza",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/44fdv2.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Zamasu",
  grade: "Or",
  category: "Legend SSP",
  images: "",
  card: "https://files.catbox.moe/163ro4.jpg",
  Price: "520nc",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Zenitsu",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/fqil2d.jpg",
  Price: "200k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Zeno",
  grade: "Bronze",
  category: "Sparking SP",
  images: "",
  card: "https://files.catbox.moe/cem49v.jpg",
  Price: "400k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Zenon",
  grade: "Or",
  category: "Ultra SM",
  images: "",
  card: "https://files.catbox.moe/ezuqry.jpg",
  Price: "1m",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Zeref",
  grade: "Argent",
  category: "Sparking S",
  images: "",
  card: "https://files.catbox.moe/7than2.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Zohakuten",
  grade: "Bronze",
  category: "Ultra SP",
  images: "",
  card: "https://files.catbox.moe/1yh0jf.jpg",
  Price: "400k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Zora",
  grade: "Bronze",
  category: "Sparking SM",
  images: "",
  card: "https://files.catbox.moe/dgoqx7.jpg",
  Price: "100k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
},
{
  name: "Zorro",
  grade: "Argent",
  category: "Ultra SM",
  images: "",
  card: "https://files.catbox.moe/h2cvdu.jpg",
  Price: "500k",
  specs: "force:, speed:, attacks:",
  Moves: "",
  Patterns: ""
}
];


function generateSpecs(grade, placement) {
  return `Specs pour ${grade} - ${placement || 'standard'}`;
}
function generateMoves(name) {
  return `Moves de ${name}`;
}
function generatePatterns(name) {
  return `Patterns de ${name}`;
}

// --- Détermination du prix ---
function determinePrice(pricePart) {
  pricePart = pricePart.toLowerCase();
  let total = 0;
  const priceRegex = /(\d+)([km]?)/g;
  let match;
  while ((match = priceRegex.exec(pricePart)) !== null) {
    const value = parseInt(match[1]);
    const unit = match[2];
    if (unit === 'k') total += value * 1000;
    else if (unit === 'm') total += value * 1_000_000;
    else total += value;
  }
  return { price: total, unit: "golds" };
}

// --- Catégorie simplifiée ---
function determineCategory(categoryPart) {
  switch (categoryPart.toLowerCase()) {
    case 'sm': return 's-';
    case 'sp': return 's+';
    case 's': return 's';
    case 'ssm': return 'ss-';
    case 'ssp': return 'ss+';
    case 'ss': return 'ss';
    default: return 'inconnu';
  }
}

// --- Création d'une carte depuis un objet existant ---
function createCard(cardObj) {
  const priceData = determinePrice(cardObj.price);
  return {
    name: cardObj.name,
    grade: cardObj.grade,
    placement: cardObj.placement || 'standard',
    category: determineCategory(cardObj.category),
    price: priceData.price,
    unit: priceData.unit,
    image: cardObj.card,
    specs: generateSpecs(cardObj.grade, cardObj.placement),
    Moves: generateMoves(cardObj.name),
    Patterns: generatePatterns(cardObj.name)
  };
}

// --- Grouper les cartes par placement ---
function groupCardsByPlacement(cardsArray) {
  const groupedCards = {};
  for (const card of cardsArray) {
    const placement = card.placement;
    if (!groupedCards[placement]) groupedCards[placement] = [];
    groupedCards[placement].push({
      grade: card.grade,
      name: card.name,
      category: card.category,
      image: card.image,
      price: card.price,
      unit: card.unit
    });
  }
  return groupedCards;
}

// --- Génération finale ---
const allCards = cards.map(c => createCard(c));
const cardData = groupCardsByPlacement(allCards);

module.exports = { cards: cardData };
 
